name: hookui-ci

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Check libcs2
      uses: actions/checkout@v3
      with:
        repository: Captain-Of-Coit/libcs2
        token: ${{ secrets.GH_PAT }}
        path: libcs2/
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '21.1.0'
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: make build
