name: hookui-ci

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bepinex-version: [5, 6]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Checkout libcs2
        uses: actions/checkout@v3
        with:
          repository: Captain-Of-Coit/libcs2
          token: ${{ secrets.GH_PAT }}
          path: libcs2/
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build (BepInEx ${{ matrix.bepinex-version }})
        run: make package-unix BEPINEX_VERSION=${{ matrix.bepinex-version }}
      - name: Upload Artifact (BepInEx ${{ matrix.bepinex-version }})
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ github.sha }}-bepinex-${{ matrix.bepinex-version }}
          path: dist/*.dll